---
title: "Practicum A&E — Introduction to R and RStudio"
author: "Susane Ribeiro Gomes"
output:
  html_document: default
  pdf_document: default
---

## Dataset description

This analysis uses the Schoolplezier dataset developed for the Assessment & Evaluation practicum. 
Variable `sekse` is coded as 1 = meisje (girl), 2 = jongen (boy).

---

## Load packages

```{r}
library(lavaan)
library(ggplot2)
library(dplyr)
library(haven)
library(semTools)
library(psych)
D <- read.table(
  "Schoolplezier.dat",
  header = TRUE,
  sep = "\t"
)

summary(D)
head(D)
dim(D)

summary(D$leeftijd)

sum(is.na(D$sekse))
colSums(is.na(D[, 5:12]))

item_means <- colMeans(D[, 5:12], na.rm = TRUE)
item_sds   <- apply(D[, 5:12], 2, sd, na.rm = TRUE)

item_means
item_sds

table(D$sekse, useNA = "always")

item_rec <- 5 - D[, 5:10]
colnames(item_rec) <- colnames(D[, 5:10])

Drec <- cbind(D[, 1:4], item_rec, D[, 11:12])

corr <- cor(Drec[, 5:12], use = "pairwise")
round(corr, 3)

diag(corr) <- NA

min(corr, na.rm = TRUE)
max(corr, na.rm = TRUE)

which(corr == min(corr, na.rm = TRUE), arr.ind = TRUE)
which(corr == max(corr, na.rm = TRUE), arr.ind = TRUE)

model1 <- "
f1 =~ item1 + item2 + item4 + item7
f2 =~ item3 + item5 + item6 + item8
"

fit1 <- cfa(model1, data = Drec)

summary(fit1, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

compRelSEM(fit1)
AVE(fit1)
fit2 <- cfa(model1, data = Drec, std.lv = TRUE)

summary(fit2, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

AVE(fit2)
modelcross <- "
f1 =~ item1 + item2 + item4 + item7 + item6
f2 =~ item3 + item5 + item6 + item8
item6 ~~ item2
"

fit_cross <- cfa(modelcross, data = Drec, std.lv = TRUE)

summary(fit_cross, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

AVE(fit_cross)
fa.diagram(fa(Drec[, 5:12], nfactors = 2))

fa(D[, 5:12], nfactors = 2)$communality
fa(D[, 5:12], nfactors = 2)$Vaccounted




